# Generated by Django 3.1.5 on 2021-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_data_publikacji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='description',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='rejestracja',
            field=models.CharField(default='', max_length=70),
        ),
    ]
